---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginx-http
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "1180"
          - name: HTTPS_PORT
            value: "11443"
        ports:
        - containerPort: 1180
          name: mtool-http
        - containerPort: 11443
          name: mtool-https

---
apiVersion: v1
kind: Service
metadata:
  name: service-test
spec:
  selector:
    app: nginx
  ports:
  - name: service-nginx-http
    protocol: TCP
    port: 80
    targetPort: nginx-http
  - name: service-multitool-http
    protocol: TCP
    port: 1180
    targetPort: mtool-http
  - name: service-multitool-https
    protocol: TCP
    port: 11443
    targetPort: mtool-https

---
apiVersion: v1
kind: Pod
metadata:
  name: multitool-test-pod
spec:
  containers:
  - name: multitool-test-pod
    image: wbitt/network-multitool