{
 "title": "netology-test",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "memFree",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"})/(1024^2)"
    }
   ]
  },
  {
   "title": "утилизация CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "100 - avg by(instance) (irate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "CPU average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{}[$__rate_interval]))"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{}[$__rate_interval]))"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "free filesystem space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}"
    }
   ]
  }
 ]
}