---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginx-http
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
        ports:
        - containerPort: 8080
          name: mtool-http

---
apiVersion: v1
kind: Service
metadata:
  name: service-test
spec:
  selector:
    app: nginx
  ports:
  - name: service-nginx-http
    protocol: TCP
    port: 9001
    targetPort: nginx-http
  - name: service-multitool-http
    protocol: TCP
    port: 9002
    targetPort: mtool-http

---
apiVersion: v1
kind: Pod
metadata:
  name: multitool-test-pod
spec:
  containers:
  - name: multitool-test-pod
    image: wbitt/network-multitool