apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: nginx-http
    protocol: TCP
    port: 9001
    targetPort: nginx-http
    nodePort: 30081
  - name: mtool-http
    protocol: TCP
    port: 9002
    targetPort: mtool-http
    nodePort: 30082