apiVersion: apps/v1
kind: Deployment
metadata:
  name: roll-deployment
spec:
  replicas: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:  
      maxSurge: 5
      maxUnavailable: 1
  selector:
    matchLabels:  
      app: nginx
  template:
    metadata:  
      labels:  
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.28
          ports:  
            - containerPort: 80
        - name: multitool-container
          image: wbitt/network-multitool
          ports:  
            - containerPort: 8888
          env:
            - name: HTTP_PORT  
              value: "8888"